### ISSUE TITLE
Introduce the concept of superuser

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumukit-auth#6]
We need to embed into the auth token not only slugs with grants, but also a "sudo" concept, that assigns the user extra permissions:
- in atheneum, a superuser should be able to admin the components she has access to - see exams, change organization details, etc
- in editor, a superuser should be able to destroy content - e.g. destroy exercises
- in classroom, only superusers should be able to create courses.

**Comment by flbulgarelli** [comment]
@matifreyre @mmatos @faloi @fedescarpa

**Comment by faloi** [comment]
Agree.

**Comment by fedescarpa** [comment]
+1

**Comment by matifreyre** [comment]
+1
